name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your first issue to whatsapp-osint! I really appreciate your interest and hope you enjoy the repository."
        pr-message: "Thanks for your first Pull Request to whatsapp-osint! I really appreciate people helping me maintain the project."
